var z = Zero

console.log('isNull ', z.object.isNull(null), z.object.isNull(undefined))
console.log('isUndefined ', z.object.isUndefined(undefined), z.object.isUndefined(null))
console.log('isNumber ', z.object.isNumber(1), z.object.isNumber('1'))
console.log('isString ', z.object.isString(''), z.object.isString(1))
console.log('isBoolean ', z.object.isBoolean(true), z.object.isBoolean(''))
console.log('isArray ', z.object.isArray([]), z.object.isArray({}))
console.log('isObject ', z.object.isObject({}), z.object.isObject(function () {}))
console.log('isFunction ', z.object.isFunction(function () {}), z.object.isFunction({}))
console.log('isDomElement ', z.object.isDomElement(document.getElementById('dom')), z.object.isDomElement(1))
console.log('isRegExp ', z.object.isRegExp(/asd/), z.object.isRegExp({}))
console.log('isDate ', z.object.isDate(new Date()), z.object.isDate({}))
console.log('isBuffer ', true, z.object.isBuffer({}))
console.log('qs.stringify ', z.qs.stringify({ a: 1, b: { c: 'c', d: { e: 'e', r: { a: 1 } } }, c: 3 }) === 'a=1&b%5Bc%5D=c&b%5Bd%5D%5Be%5D=e&b%5Bd%5D%5Br%5D%5Ba%5D=1&c=3')
console.log('qs.parse ', z.qs.parse('a=1&b%5Bc%5D=c&b%5Bd%5D%5Be%5D=e&b%5Bd%5D%5Br%5D%5Ba%5D=1&c=3'))
console.log('qs.get ', z.qs.get())
console.log('extend ', z.object.extend({ a: [1, 2] }, { a: [3], b: 2 }))
console.log('complement ', z.number.complement('-1', 3))
console.log('format ', z.date.format(new Date().getTime(), 'YYYY-MM-DD a hh:mm:ss'))
console.log('flat ', z.array.flat([1, [2, [3]]]))
console.log('random ', z.math.random(1, 10))
console.log('diff ', z.date.diff('2018/01/01', '2018/01/02 13:00:00', 'H'))
document.getElementById('throttle').addEventListener('click', z.util.throttle(function () { console.log('throttle ') }, 1000))
document.getElementById('debounce').addEventListener('click', z.util.debounce(function () { console.log('debounce ', this, 'agrs', arguments) }, 1000))

const add = function (a, b, c) { return a + b + c }
const curryAdd = z.util.curry(add)
console.log('curry', curryAdd(1)(2)(3), curryAdd(1, 2)(3), curryAdd(1)(2, 3))
console.log('userAgent', z.util.userAgent)
